when:
  - event: ["push", "manual"]
    branch: ["master"]
  - event: ["pull_request"]
    branch: ["master"]

engine: "nixery"

clone:
  skip: false
  depth: 1
  submodules: false

dependencies:
  nixpkgs:
    - nodejs

environment:
  NODE_ENV: "production"

steps:
  - name: "Install surfer"
    command: npm -g install cloudron-surfer
  - name: "Upload"
    command: $(npm config get prefix)/bin/surfer put --token "$SURFER_TOKEN" --server "$SURFER_HOST" ./* "$SURFER_FOLDER"
    environment:
      ALFA: BRAVO
